---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 3.5-jdk8

inputs:
- name: boot-daemon

caches:
- path: boot-daemon/.gradle

outputs:
- name: built-artifact

run:
  path: ./boot-daemon/ci/tasks/scripts/build-debian.sh
  user: root

