---
platform: linux

image_resource:
  type: docker-image
  source: {repository: xueshanf/awscli}

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

inputs:
- name: boot-daemon
- name: packer-manifest

run:
  path: ./boot-daemon/ci/tasks/scripts/tag-ami.sh
