---
platform: linux

image_resource:
  type: docker-image
  source: {repository: sneakybeaky/kitchen-ec2}

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

inputs:
- name: boot-daemon
- name: debian-candidate-package

run:
  path: ./boot-daemon/ci/tasks/scripts/test-package.sh
